-- 예시 테이블
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
    CODE         VARCHAR2(2 BYTE)  NOT NULL UNIQUE, 
    MODEL        VARCHAR2(10 BYTE) NULL, 
    CATEGORY     VARCHAR2(5 BYTE)  CHECK(CATEGORY = 'MAIN' OR CATEGORY = 'SUB'),
    PRICE        NUMBER            CHECK(PRICE >= 0),
    AMOUNT       NUMBER(2)         CHECK(AMOUNT >= 0 AND AMOUNT <= 100),
    MANUFACTURED DATE
);

