--데이터베이스 오브젝트 설계 1 부서 

CREATE TABLE ONE_01 (
 
 DEPT_NO VARCHAR2(15) NOT NULL,
 DEPT_NAME VARCHAR2(30),
 DEPT_LOCATION VARCHAR2(50),
 CONSTRAINT FINALLY PRIMARY KEY(DEPT_NO)
 );
 
 CREATE TABLE ONE_0101(
 
 EMP_NO NUMBER NOT NULL,
 DEPT_NO VARCHAR2(15),
 POSITION_1 CHAR(10),
 NAME_1 VARCHAR2(15),
 HIRE_DATE VARCHAR2,
 SALARY NUMBER,
 CONSTRAINT FINALLY22 PRIMARY KEY(EMP_NO),
 CONSTRAINT FK_DEPT_NO FOREIGN KEY(DEPT_NO)
 );
 
 
 
 
 
 
 --데이터 베이스 오브젝트 설계 2 사원
 
 CREATE TABLE TWO_02(
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30),
    BEGIN_DATE DATE,
    END_DATE DATE,
    CONSTRAINT FINALLY2 PRIMARY KEY(PJT_NO)
    );
    
    

CREATE TABLE TWO_022(
    PJT_NO NUMBER
    PJT_NAME VARCHAR2(30)
    BEGIN_DATE DATE
    END_DATE DATE
    
