-- PK 

--테이블 삭제
DROP TABLE ORDER_TBL;
DROP TABLE PRODUCT_TBL;

--만들기 전에 지우는거 넣어놓자

-- 제품 테이블(부모 테이블)
CREATE TABLE PRODUCT_TBL (
    PROD_NO NUMBER NOT NULL,
    PROD_NAME VARCHAR2(10 BYTE),
    PROD_PRICE NUMBER,
    PROD_STOCK NUMBER,
    CONSTRAINT PK_PROD PRIMARY KEY(PROD_NO)
);

-- 주문 테이블(자식 테이블)
CREATE TABLE ORDER_TBL(
    ORDER_NO NUMBER NOT NULL, 
    USER_ID VARCHAR2(10 BYTE),
    PROD_NO NUMBER ,
    ORDER_DATE DATE,
    CONSTRAINT PK_ORDER PRIMARY KEY(ORDER_NO),
    CONSTRAINT FK_ORDER_PROD FOREIGN KEY(PROD_NO) REFERENCES PRODUCT_TBL(PROD_NO)
);

--제약조건 테이블

--테이블 구조 확인하는 테이블 
--DESCRIBE ALL_CONSTRAINTS;

-- SELECT * FROM ALL_CONSTRAINTS WHERE CONSTRAINT_NAME LIKE 'PK%';


    