-- 임플로이즈의 구조 파악
DESC EMPLOYEES; --최대 네글자까지 줄일 수 있음 DESC 네글자 이하로 내려가면 안됨 

--1. EMPLOYEES 테이블에서 FIST_NAME, LAST_NAME 조회하기 
--SELECT E.FIRST_NAME AS FNAME, E.LAST_NAME AS LNAME
--  FROM HR.EMPLOYEES E;
  
  SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES;
--2. EMPLOYEES 테이블에서 DEPARTMENT_ID를 조회하는데 중복제거하고 조회하기 
SELECT DISTINCT DEPARTMENT_ID
    FROM EMPLOYEES;
    
--3 EMPLOYEES 테이블에서 EMPLOYEE_ID가 150인 사원 조회 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
    FROM EMPLOYEES
WHERE EMPLOYEE_ID = 150; -- WHERE(조건)의 등호(=)는 비교 연산자이다. 

--4. EMPLOYEES 테이블에 SALARY가 10000 ~ 20000 사이 사원 조회 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
    FROM EMPLOYEES
    WHERE SALARY BETWEEN 10000 AND 20000;
    
--5. EMPLYEES 테이블에서 DEPARTMENT_ID가 30, 40, 50인 사원 조회하기 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IN(30,40,50);
    
--6, 임플로이 테이블에서 디팔트먼트 아이디가 널인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NULL; -- IS NOT NULL
 
--7. EMPLOYEES 테이블에서 PHONE_NUMBER ' 515 '로 시작하는 사원 조회하기 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
  FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '515___'; -- % : 모든 텍스트가 허용되는 만능 문자 

--8. EMPLOYEES 테이블을 FIRST_NAME의 가나다순(오름차순: Asending Sort)으로 정렬해서 조회하기 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
    FROM EMPLOYEES
 ORDER BY FIRST_NAME ASC;
 
--9. EMPLOYEES 테이블을 높은 SALARY(내림차순: Descending)를 받는 사원을 먼저 조회하기 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
    FROM EMPLOYEES
 ORDER BY SALARY DESC; -- Descending은 반드시 적어줘야 함 

--10. EMPLOYEES 테이블 사원들을 DEPARTMENT_ID 순으로 조회하고 동일한 DEPARTMENT_ID를 가진 사원들은 높은 SALARY순으로 조회하시오
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
    FROM EMPLOYEES
 ORDER BY DEPRTMENT_ID ASC, SALARY DESC;
 
--11. 
 
 