DROP TABLE THREE_TABLE;
DROP TABLE SUBJECT;
DROP TABLE SUBJECT_TABLE;


-- 학생 테이블 
CREATE TABLE STUDENT (
    PROD SCHOOL_NO VARCHAR2(5 BYTE) NOT NULL,
    PROD_NAME VARCHAR2(15 BYTE),
    PROD_AGE NUMBER(3),
    CONSTRAINT PK_PROD_SCHOOL_NO PRIMARY KEY(SCHOOL_NO)
);

-- 과목 테이블 생성
CREATE TABLE SUBJECT (
    SCHOOL_NO NUMBER NOT NULL,
    SJBJECT_NO VARCHAR2(10 BYTE),
    PROFESSOR VARCHAR2(15 BYTE) NULL,
    CONSTRAINT COLLA PRIMARY KEY(SCHOOL_NO),
    CONSTRAINT NEW_CONNECT FOREIGN KEY(SCHOOL_NO) REFERENCES STUDENT(SCHOOL_NO) --PK + FK
);

CREATE TABLE THREE_TABLE(
    ENR_NO NUMBER NOT NULL,
    STU_NO   VARCHAR2(5 BYTE) NOT NULL,
    SJT_CODE VARCHAR2(1 BYTE) NOT NULL,
    CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT(SCHOOL_NO),
    CONSTRAINT FK_ENROLL_SUBJECT FOREIGN KEY(SJT_CODE) REFERENCES SUBJECT(SJBJECT_NO)
  );  


